sequenceDiagram
    participant vendor as Firmware Vendor
    participant log as Log Operator
    participant update as Update Client
    participant flash as Device Flash
    participant bootloader as Device bootloader

    opt Notify clients
        activate vendor
        vendor --X update: New update available
        deactivate vendor
    end

    rect rgba(80,80,80,0.1)
        note right of log: Client update
        activate update
        update ->> update: Trigger Update
        update ->>+ flash: Fetch previous STH
        flash -->>- update: STH_old
        update ->>+ log: GetConsistencyProofRequest{STH_update, STH_old}
        log -->>- update: GetConsistencyProofResponse
        update ->> update: Verify
        opt Verification successful
            update ->>+ flash: Write Firmware + Proof Bundle
            flash -->>- update: Write OK
            rect rgba(0,192,0,0.3)
                opt If write OK
                    update ->>+ flash: Set active partition
                    flash -->>- update: OK
                end
            end
        end
    end
